### ISSUE TITLE
for hours 2 or 3 days a week, change the punctuation for headings

### ISSUE THREAD

**Issue by cydharrell** [JudicialCouncilOfCalifornia/ftrc#35]
when a court or court resources has open hours on 2 days that aren't contiguous, our display makes it look like there are hours on the middle days. Example: the Contra Costa Richmond courthouse - here are its data and how it appears 
<img width="315" alt="screen shot 2019-02-04 at 1 31 28 pm" src="https://user-images.githubusercontent.com/5133498/52238595-36652000-2881-11e9-9892-acd68985ab80.png">

<img width="717" alt="screen shot 2019-02-04 at 1 29 07 pm" src="https://user-images.githubusercontent.com/5133498/52238531-10d81680-2881-11e9-99b3-9bafe68b913c.png">

I *think* the right solution is to display a comma rather than a hyphen here, but I don't know how the code is actually set up. need the help of an info &/or front-end designer to get this right.

**Comment by exygy-dev** [comment]
### Acceptance Criteria
Given that more than 1 day has the same hours and 2 or more days are consecutive, then the hours will be displayed as [Day 1]-[Day n]: [hours] where Day 1 is the first day in the consecutive series and Day n is the last day in the consecutive series.

Given that more than 1 day has the same hours and the days are non-consecutive, then the hours will be displayed as [Day 1], ...., [Day n]: [hours] where Day 1 is the first day in the non-consecutive series and Day n is the last day in the non-consecutive series.

### Examples of this logic in place
|Example|Displays as|
|Tu & Thu both have 8:00AM - 5:00PM|Tu, Thu: 8:00AM - 5:00PM|
|M & W & F are all Closed|M, W, F: Closed|

**Comment by jaredcwhite** [comment]
Fixed and pushed

**Comment by cydharrell** [comment]
Checked & also re-checked with the court that reported it. Good to go, closing now.
