### ISSUE TITLE
don't force capitalization in the Matters Served dropdown

### ISSUE THREAD

**Issue by cydharrell** [JudicialCouncilOfCalifornia/ftrc#36]
Right now we seem to be forcing a model of "capitalize first letter only" within the Matters Served dropdown list. However, in some counties there are important acronyms within the list (such as DCSS). We need to just use the case that's in the data.

<img width="924" alt="screen shot 2019-02-05 at 9 04 06 am" src="https://user-images.githubusercontent.com/5133498/52290624-4afaf400-2925-11e9-8d6f-68c6f1221104.png">

**Comment by jaredcwhite** [comment]
Fixed and pushed

**Comment by cydharrell** [comment]
Looks good & re-checked with the court that reported it. Closing now.
