### ISSUE TITLE
FTRC doesn't work for IE browsers - returns a blank page

### ISSUE THREAD

**Issue by cydharrell** [JudicialCouncilOfCalifornia/ftrc#37]
this is coming from 2 reports from Courts - people using IE11 on desktop, and Mel Wong verified it internally. on IE, going directly to the Heroku app returns a blank page. If you instead go to the testing URL at https://www4.courtinfo.ca.gov/fmrc/ui-test.htm, you see the search box on courtinfo.ca.gov but when you enter a zip or city and press search, nothing loads.

**Comment by cydharrell** [comment]
screenshot from Jenny - the prompt doesn't show on the input screen in IE11 
![image](https://user-images.githubusercontent.com/5133498/52316597-f2e9df00-2970-11e9-9e68-54e19c418a99.png)

**Comment by cydharrell** [comment]
in case this helps with investigating https://twitter.com/josiahrooney/status/1093192314984398848

**Comment by jaredcwhite** [comment]
Fixed and pushed!
