### ISSUE TITLE
winnow & compress content at top of results page

### ISSUE THREAD

**Issue by cydharrell** [JudicialCouncilOfCalifornia/ftrc#39]
Based on early research & stakeholder feedback, we need to make changes to the design of the top of the results page. Screenshot below. Elements of the changes are:

- Remove the dotted line section separator
- Move the "There are X courthouse locations" headline up directly under the "The jurisdiction for [ZIP] is Y Superior Court"
- Remove the Matters Served dropdown and "what's this" link
- Generally remove excess white spaces in this section of the page
- Associate the "self help locations" checkbox more closely with the top of the results table
- Continue suppressing both the "There are X courthouse locations" line and the "self help locations only" checkbox when only one courthouse location is returned.
 
![image](https://user-images.githubusercontent.com/5133498/53257071-253c5180-367e-11e9-9b54-7608e58e5d9c.png)

**Comment by jaredcwhite** [comment]
Fixed and pushed 😉
(yes really, I worked on this earlier in the morning…)
