### ISSUE TITLE
Two courthouse address typos

### ISSUE THREAD

**Issue by bennlich** [JudicialCouncilOfCalifornia/ftrc#47]
Found a couple of small typos in two courthouse addresses:

![Screenshot from 2019-04-12 13-25-18](https://user-images.githubusercontent.com/704368/56065938-278c6500-5d2b-11e9-9b3e-eeb0e265f18b.png)

The Alameda address should be Shore Line Drive instead of Shoreline Drive.

The Berkeley courthouse address has an extra comma inserted between King and Jr.

cc @melwong-jcc

**Comment by melwong-jcc** [comment]
Alameda and Berkeley corrections applied to courthouse data.

**Comment by bennlich** [comment]
That was quick!
